; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3]
platform                = espressif32
board                   = esp32-s3-devkitc-1
framework               = espidf
monitor_speed           = 921600
upload_speed            = 921600
board_build.f_cpu       = 240000000L
monitor_filters         = esp32_exception_decoder

; memory configuration
board_build.flash_size          = 16MB
board_upload.flash_size         = 16MB
board_upload.maximum_size       = 16777216
board_build.partitions          = partitions.csv
board_build.arduino.memory_type = qspi_opi

; external libraries
lib_deps = 
    https://github.com/AlisonTristao/TinyShell
    https://github.com/AlisonTristao/TinyEKF

lib_extra_dirs = utils

build_flags = 
    -I robot
    -I include
    -I utils
    -D LOG_ALL
    -std=gnu++2a
    -DMAC_ADDR=0xDC,0xDA,0x0C,0x30,0xAA,0x5C
    -DBAUDRATE=5000000
    -DENABLE_SYSTEM_MONITOR=1
    -fexceptions

upload_flags = 
    --no-stub

build_unflags = 
    -std=gnu++1
    -fno-exceptions