#include <unity.h>

#include <KeyStore.h>
#include <btp/codec.hpp>

#include <cstdint>
#include <cstring>

namespace {

// ---------------------------------------------------------------------------
// Golden vector, generated by the provisioner itself. This is the seed of the
// acceptance criterion "all three ends derive the same key": the dongle and
// TraceView are to be compared against these very octets.
//
// Passwords that produced it -- the other two tasks need exactly these:
//     key E (channel B, TraceView <-> robot): "senha-e-de-teste"
//     key L (channel C, dongle    <-> robot): "senha-l-de-teste"
//
// Reproduce with:
//     python scripts/provision_key.py --force \
//         --password-e senha-e-de-teste --password-l senha-l-de-teste \
//         bally.key
//
// (--password-* is the provisioner's test-only, non-interactive path; a real
// card is provisioned by typing the passwords.)
// ---------------------------------------------------------------------------
const std::uint8_t kGoldenFile[KeyStore::kFileSize] = {
    0x42, 0x54, 0x50, 0x4B, 0x45, 0x59, 0x00, 0x00,  // 00 magic "BTPKEY\0\0"
    0x02, 0x00, 0x01, 0x00, 0x40, 0x0D, 0x03, 0x00,  // 08 format/cipher/kdf/-/iters
    0x62, 0x61, 0x6C, 0x6C, 0x79, 0x2D, 0x6B, 0x64,  // 16 salt "bally-kd
    0x66, 0x2D, 0x73, 0x61, 0x6C, 0x74, 0x2D, 0x31,  // 24 f-salt-1"
    0xDC, 0x13, 0xA1, 0x79, 0x86, 0x01, 0xE4, 0x24,  // 32 key_e
    0xC4, 0x5F, 0x69, 0x1D, 0xD5, 0x48, 0x4E, 0xED,  // 40
    0xE2, 0x8B, 0x8E, 0xDF, 0xD9, 0x19, 0xD3, 0x9F,  // 48 key_l
    0x5B, 0x57, 0x3C, 0x92, 0xB7, 0x72, 0x24, 0xD7,  // 56
    0xC7, 0xA4, 0x5E, 0x15, 0xA4, 0x1B, 0x78, 0x0F,  // 64 verify_e
    0x2A, 0x5E, 0x4D, 0xDC, 0x86, 0x6F, 0x8A, 0x08,  // 72 verify_l
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // 80 reserved
    0x00, 0x00, 0x00, 0x00, 0xC8, 0xB9, 0x19, 0xC7,  // 88 reserved + crc32
};

const std::uint8_t kGoldenKeyE[KeyStore::kKeyLength] = {
    0xDC, 0x13, 0xA1, 0x79, 0x86, 0x01, 0xE4, 0x24,
    0xC4, 0x5F, 0x69, 0x1D, 0xD5, 0x48, 0x4E, 0xED,
};
const std::uint8_t kGoldenKeyL[KeyStore::kKeyLength] = {
    0xE2, 0x8B, 0x8E, 0xDF, 0xD9, 0x19, 0xD3, 0x9F,
    0x5B, 0x57, 0x3C, 0x92, 0xB7, 0x72, 0x24, 0xD7,
};
const std::uint8_t kGoldenVerifyE[KeyStore::kVerifyLength] = {
    0xC7, 0xA4, 0x5E, 0x15, 0xA4, 0x1B, 0x78, 0x0F,
};
const std::uint8_t kGoldenVerifyL[KeyStore::kVerifyLength] = {
    0x2A, 0x5E, 0x4D, 0xDC, 0x86, 0x6F, 0x8A, 0x08,
};

constexpr std::uint32_t kExpectedIterations = 200000U;
constexpr std::size_t kOffKeyE = 32U;
constexpr std::size_t kOffKeyL = 48U;
constexpr std::size_t kOffCrc = 92U;

// Working copy so a test can corrupt one field without disturbing the next.
struct Image {
    std::uint8_t data[KeyStore::kFileSize];

    Image() { std::memcpy(data, kGoldenFile, sizeof(data)); }

    // Rewrites the trailing CRC so that a deliberate change to a *payload*
    // field is not reported as crc32. Without this, a flipped key octet would
    // stop at the CRC check and never reach verify_e, which is precisely the
    // check under test.
    void restamp_crc() {
        const std::uint32_t crc = btp::crc32(data, kOffCrc);
        data[kOffCrc + 0U] = static_cast<std::uint8_t>(crc);
        data[kOffCrc + 1U] = static_cast<std::uint8_t>(crc >> 8U);
        data[kOffCrc + 2U] = static_cast<std::uint8_t>(crc >> 16U);
        data[kOffCrc + 3U] = static_cast<std::uint8_t>(crc >> 24U);
    }
};

void assert_fails_naming(const std::uint8_t* data, std::size_t size,
                         KeyStore::Error expected, const char* field) {
    KeyStore store;
    TEST_ASSERT_FALSE(store.load(data, size));
    TEST_ASSERT_FALSE(store.loaded());
    TEST_ASSERT_EQUAL_UINT8(static_cast<std::uint8_t>(expected),
                            static_cast<std::uint8_t>(store.last_error()));
    TEST_ASSERT_EQUAL_STRING(field, KeyStore::error_field(store.last_error()));
    // A rejected file must leave nothing reachable to use as a key.
    TEST_ASSERT_NULL(store.key_e());
    TEST_ASSERT_NULL(store.key_l());
}

// ---------------------------------------------------------------------------
// A valid file parses and hands over both keys.
// ---------------------------------------------------------------------------
void test_golden_file_parses_and_delivers_both_keys() {
    KeyStore store;
    TEST_ASSERT_TRUE(store.load(kGoldenFile, sizeof(kGoldenFile)));
    TEST_ASSERT_TRUE(store.loaded());
    TEST_ASSERT_EQUAL_UINT8(static_cast<std::uint8_t>(KeyStore::Error::Ok),
                            static_cast<std::uint8_t>(store.last_error()));
    TEST_ASSERT_EQUAL_UINT32(kExpectedIterations, store.iterations());

    TEST_ASSERT_NOT_NULL(store.key_e());
    TEST_ASSERT_NOT_NULL(store.key_l());
    TEST_ASSERT_EQUAL_UINT8_ARRAY(kGoldenKeyE, store.key_e(),
                                  KeyStore::kKeyLength);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(kGoldenKeyL, store.key_l(),
                                  KeyStore::kKeyLength);
    // The two keys must not be the same secret wearing two hats: that is the
    // whole reason there are two independent passwords.
    TEST_ASSERT_NOT_EQUAL(0, std::memcmp(store.key_e(), store.key_l(),
                                         KeyStore::kKeyLength));

    // Public tags: these are what may be printed, and what the dongle and
    // TraceView will be compared against.
    TEST_ASSERT_EQUAL_UINT8_ARRAY(kGoldenVerifyE, store.verify_e(),
                                  KeyStore::kVerifyLength);
    TEST_ASSERT_EQUAL_UINT8_ARRAY(kGoldenVerifyL, store.verify_l(),
                                  KeyStore::kVerifyLength);

    store.unload();
    TEST_ASSERT_FALSE(store.loaded());
    TEST_ASSERT_NULL(store.key_e());
    TEST_ASSERT_NULL(store.key_l());
}

// ---------------------------------------------------------------------------
// Wrong length, named "size". Both directions: a card whose write was cut
// short, and a file that grew past the format.
// ---------------------------------------------------------------------------
void test_wrong_size_fails_naming_size() {
    assert_fails_naming(kGoldenFile, KeyStore::kFileSize - 1U,
                        KeyStore::Error::Size, "size");
    assert_fails_naming(kGoldenFile, 0U, KeyStore::Error::Size, "size");
    assert_fails_naming(nullptr, KeyStore::kFileSize, KeyStore::Error::Size,
                        "size");

    std::uint8_t oversized[KeyStore::kFileSize + 1U] = {};
    std::memcpy(oversized, kGoldenFile, KeyStore::kFileSize);
    assert_fails_naming(oversized, sizeof(oversized), KeyStore::Error::Size,
                        "size");
}

// ---------------------------------------------------------------------------
// Not a bally.key at all, named "magic" -- checked before anything else in
// the body, and before the CRC, so "wrong file" never reads as "corrupt
// file".
// ---------------------------------------------------------------------------
void test_wrong_magic_fails_naming_magic() {
    Image image;
    image.data[0] = 'X';
    image.restamp_crc();  // a good CRC must not rescue a foreign file
    assert_fails_naming(image.data, sizeof(image.data),
                        KeyStore::Error::Magic, "magic");

    // The two NUL octets are part of the magic, not padding.
    Image trailing;
    trailing.data[7] = 0x01U;
    trailing.restamp_crc();
    assert_fails_naming(trailing.data, sizeof(trailing.data),
                        KeyStore::Error::Magic, "magic");
}

// ---------------------------------------------------------------------------
// The header octets the robot refuses to guess about.
// ---------------------------------------------------------------------------
void test_wrong_header_octets_fail_naming_their_field() {
    Image format;
    format.data[8] = 0x01U;  // one-key file: not what this firmware reads
    format.restamp_crc();
    assert_fails_naming(format.data, sizeof(format.data),
                        KeyStore::Error::Format, "format");

    Image cipher;
    cipher.data[9] = 0x01U;  // ChaCha20-Poly1305 needs 32-octet keys
    cipher.restamp_crc();
    assert_fails_naming(cipher.data, sizeof(cipher.data),
                        KeyStore::Error::Cipher, "cipher");

    Image kdf;
    kdf.data[10] = 0x02U;
    kdf.restamp_crc();
    assert_fails_naming(kdf.data, sizeof(kdf.data), KeyStore::Error::Kdf,
                        "kdf");
}

// ---------------------------------------------------------------------------
// Corruption, named "crc32". Both a damaged CRC field and a damaged body.
// ---------------------------------------------------------------------------
void test_corrupted_crc_fails_naming_crc32() {
    Image damaged_crc;
    damaged_crc.data[kOffCrc] = static_cast<std::uint8_t>(
        damaged_crc.data[kOffCrc] ^ 0xFFU);
    assert_fails_naming(damaged_crc.data, sizeof(damaged_crc.data),
                        KeyStore::Error::Crc32, "crc32");

    // The reserved octets are covered too, so a future field cannot be
    // slipped in without invalidating readers that predate it.
    Image damaged_reserved;
    damaged_reserved.data[80] = 0x5AU;
    assert_fails_naming(damaged_reserved.data, sizeof(damaged_reserved.data),
                        KeyStore::Error::Crc32, "crc32");
}

// ---------------------------------------------------------------------------
// One flipped octet inside a key must be reported as that key's own verify
// tag, and must not disturb the diagnosis of the other one. This is the case
// the two tags exist for: a wrong password has to fail at boot, by name,
// instead of turning into a channel that quietly never works.
//
// It also pins the HMAC-SHA256 implementation, since the tags in the golden
// vector came from Python's hmac/hashlib: had the firmware's HMAC deviated by
// a single bit, the good file above would already have failed as verify_e.
// ---------------------------------------------------------------------------
void test_flipped_key_octet_is_reported_per_key() {
    Image bad_e;
    bad_e.data[kOffKeyE + 3U] = static_cast<std::uint8_t>(
        bad_e.data[kOffKeyE + 3U] ^ 0x01U);
    bad_e.restamp_crc();
    assert_fails_naming(bad_e.data, sizeof(bad_e.data),
                        KeyStore::Error::VerifyE, "verify_e");

    // Key L is untouched in bad_e, so its own diagnosis is unaffected:
    // corrupting L alone still reports verify_l, never verify_e.
    Image bad_l;
    bad_l.data[kOffKeyL + 9U] = static_cast<std::uint8_t>(
        bad_l.data[kOffKeyL + 9U] ^ 0x01U);
    bad_l.restamp_crc();
    assert_fails_naming(bad_l.data, sizeof(bad_l.data),
                        KeyStore::Error::VerifyL, "verify_l");

    // And a tag that was itself damaged, rather than the key, is reported the
    // same way -- the pair simply has to agree.
    Image bad_tag;
    bad_tag.data[64] = static_cast<std::uint8_t>(bad_tag.data[64] ^ 0x80U);
    bad_tag.restamp_crc();
    assert_fails_naming(bad_tag.data, sizeof(bad_tag.data),
                        KeyStore::Error::VerifyE, "verify_e");
}

// ---------------------------------------------------------------------------
// A failed reload must not leave the keys of the previous, good file
// reachable: the caller is about to report an error, not to keep running with
// key material it can no longer account for.
// ---------------------------------------------------------------------------
void test_failed_reload_discards_previous_keys() {
    KeyStore store;
    TEST_ASSERT_TRUE(store.load(kGoldenFile, sizeof(kGoldenFile)));

    Image damaged;
    damaged.data[kOffCrc + 1U] = static_cast<std::uint8_t>(
        damaged.data[kOffCrc + 1U] ^ 0xFFU);
    TEST_ASSERT_FALSE(store.load(damaged.data, sizeof(damaged.data)));
    TEST_ASSERT_FALSE(store.loaded());
    TEST_ASSERT_NULL(store.key_e());
    TEST_ASSERT_NULL(store.key_l());
    TEST_ASSERT_EQUAL_STRING("crc32", KeyStore::error_field(
                                          store.last_error()));
}

// ---------------------------------------------------------------------------
// A fresh store hands out nothing, and the SD path is a clean runtime failure
// off-target rather than a link error.
// ---------------------------------------------------------------------------
void test_fresh_store_is_empty() {
    KeyStore store;
    TEST_ASSERT_FALSE(store.loaded());
    TEST_ASSERT_NULL(store.key_e());
    TEST_ASSERT_NULL(store.key_l());
    TEST_ASSERT_NULL(store.verify_e());
    TEST_ASSERT_NULL(store.verify_l());
    TEST_ASSERT_EQUAL_UINT32(0U, store.iterations());
    TEST_ASSERT_EQUAL_STRING("ok", KeyStore::error_field(store.last_error()));
}

}  // namespace

void setUp() {}
void tearDown() {}

int main(int, char**) {
    UNITY_BEGIN();
    RUN_TEST(test_golden_file_parses_and_delivers_both_keys);
    RUN_TEST(test_wrong_size_fails_naming_size);
    RUN_TEST(test_wrong_magic_fails_naming_magic);
    RUN_TEST(test_wrong_header_octets_fail_naming_their_field);
    RUN_TEST(test_corrupted_crc_fails_naming_crc32);
    RUN_TEST(test_flipped_key_octet_is_reported_per_key);
    RUN_TEST(test_failed_reload_discards_previous_keys);
    RUN_TEST(test_fresh_store_is_empty);
    return UNITY_END();
}
