#ifndef SETTINGS_H
#define SETTINGS_H

// logger configuration (build flags)
// -> LOG_ALL
// -> LOG_INFO
// -> LOG_ERROR
// -> LOG_DEBUG

// Most of what used to live in this file (timers, EKF noise, calibration,
// most GPIO pins, ...) is now a runtime setting: see lib/RobotSettings
// (SettingsData/RobotSettings) and the "settings" shell module
// (get/set/list/save/load/reset), backed by settings.conf on the SD card.
//
// What is left here are values that genuinely cannot be a runtime SD
// setting, each with the reason next to it — not values someone forgot to
// migrate.

// -------------------- Watchdog tick --------------------
// Read in main.cpp's pre-robot.init() retry loops, before any settings can
// possibly be loaded. No real tuning value either way.
#define WDOG_TIMEOUT_TK 1  // 1 tick - quantos loops do freRTOS demoramos para excecutar novamente a task

// -------------------- Memory alias configuration (FreeRTOS task stacks) --
// Sizes the static stack arrays declared in src/main.cpp; must be a
// compile-time constant.
#define M2KB             (2 * 1024) // 2KB for the stack of the tasks, to avoid stack overflow
#define M4KB             (4 * 1024) // 4KB for the stack of the tasks, to avoid stack overflow
#define M8KB             (8 * 1024) // 8KB for the stack of the tasks, to avoid stack overflow
#define M16KB            (16 * 1024) // 16KB for the stack of the tasks, to avoid stack overflow
#define M32KB            (32 * 1024) // 32KB for the stack of the tasks, to avoid stack overflow

// -------------------- EKF model shape and coefficients --------------------
// .pio/libdeps/esp32-s3/TinyEKF/TinyEKF.h re-defines these same names (it is
// generated by that library's own optimizer.py for this exact 3-state /
// 5-measurement / 2-control differential-drive model, with the predict()/
// update() math in TinyEKF.cpp already unrolled for these dimensions and
// referencing these coefficients by name). A "setting" with these names
// would silently diverge from what the generated math actually uses, so
// they stay compile-time and in sync with the vendored header by construction.
#define EKF_STATE_DIM   3
#define EKF_MEASURE_DIM 5
#define EKF_CONTROL_DIM 2
#define EKF_WHEEL_BASE  0.30f
#define EKF_K_R         1.0f
#define EKF_K_L         1.0f
#define EKF_TAU_R       0.15f
#define EKF_TAU_L       0.15f
#define EKF_IMU_RX      0.1f
#define EKF_IMU_RY      0.1f

// -------------------- logger configuration --------------------
// here we define the data structures and definitions for the log messages,
// that will be shared between the logger and the transport protocol (e.g., esp-now)

// max espnow packet size -> 250bytes

// protocol overhead:
//   4 bytes for timestamp
// + 1 byte for type
// + 2 byte for packet number
// + 2 byte for total packets
// + 1 byte for checksum
// + 4 byte para o length
// = 14 bytes

// therefore, max message size is 250 - 14 = 236 bytes
// but, to use a size that is a multiple of 4 for better memory alignment, we will use 230 bytes for the content
// The logger uses a byte ring buffer in PSRAM. Records occupy only their header
// plus the actual payload length; the fixed ESP-NOW frame is created at flush time.
// Keep roughly the same memory budget as the previous 30,000 x 248-byte array.

// These three define the exact byte layout of `message`/`messageContent_t`
// (lib/Logger/SharedMessageTypes.h), sent over ESP-NOW to the separate
// T-Dongle receiver firmware (github.com/AlisonTristao/t_dongle_develop).
// Changing them on the robot side only would break telemetry decoding there.
#define MAX_PACKET_SIZE         250   // if we change the transport protocol, we can increase this value
#define PROTOCOL_OVERHEAD_SIZE  20    // overhead for the protocol, including timestamp, type, packet number, total packets and checksum
#define MAX_CONTENT_SIZE        229   // -1 to ensure we have space for the null terminator

// Sized once, at static-init time: `Logger ROBOT::logger` is a namespace-
// scope static (utils/BallyRobot/BallyRobot.h/.cpp), constructed before
// app_main() runs and before the SD card can possibly be mounted — its
// constructor already calls heap_caps_malloc(LOGGER_PSRAM_CAPACITY_BYTES, ...)
// at that point. Same class of problem as the SD SPI pins below.
#define LOGGER_PSRAM_CAPACITY_BYTES 7440000U // PSRAM reserved for variable-length log records
// Currently unused (wait_for_mutex() hardcodes its own timeout); kept as
// documentation of the intended value rather than migrated as a live setting.
#define LOGGER_MUTEX_TIMEOUT_MS 100   // time in ms to wait for the logger to be available - used to avoid deleting messages during printing

// -------------------- Channels --------------------
// Only referenced by the commented-out HBridge construction below
// (BallyRobot.h) — that code also references PWM_A/PWM_B, which do not
// exist anywhere in the codebase, so it does not compile as-is today.
#define CH0             0
#define CH1             1
#define CH2             2
#define CH3             3

// -------------------- OTA over Wi-Fi (DEBUG state) --------------------
// wifi.txt is already its own SD-backed, shell-editable config (see
// OTAUpdater::add_network/remove_network/wifi_add/wifi_remove); left as-is.
// OTA_MAX_NETWORKS/OTA_SSID_MAX_LEN/OTA_PASS_MAX_LEN/OTA_MAX_SCAN_RESULTS
// size fixed member/stack arrays in OTAUpdater. The timing values and
// ESPNOW_CHANNEL are read directly by OTAUpdater/ROBOT::configureCommunication
// in several places; wiring them through settings needs a small
// OTAUpdater::configure(...) API (deliberately left for a follow-up so
// ESPNOW_CHANNEL can't end up read as two different values in two places).
#define OTA_WIFI_LIST_FILE      "wifi.txt" // ssid,password per line, SD card root
#define OTA_MAX_NETWORKS        16     // max entries read from OTA_WIFI_LIST_FILE
#define OTA_SSID_MAX_LEN        33     // 32 chars + null terminator (802.11 limit)
#define OTA_PASS_MAX_LEN        65     // 64 chars + null terminator (WPA2 limit)
#define OTA_LED_STEP_MS         150    // carousel step while OTA is active
#define OTA_CONNECT_TIMEOUT_MS  8000   // per-network connect timeout
#define OTA_RETRY_SCAN_MS       5000   // delay before re-scanning when nothing matched
#define OTA_MAX_SCAN_RESULTS    20     // visible APs read back per scan
#define ESPNOW_CHANNEL          1      // channel restored after leaving OTA

// ============================================================
// Pinout da ESP32-S3
// ============================================================

// -------------------- SD Card / SPI --------------------
// Needed to physically mount the SD card, which is where settings.conf
// (everything else in this section, in every other section) lives —
// cannot be sourced from a file that isn't readable yet.
#define MISO            GPIO_NUM_6
#define SCK             GPIO_NUM_7
#define MOSI            GPIO_NUM_15
#define CS              GPIO_NUM_16

// -------------------- USB nativo --------------------
// Fixed by the ESP32-S3's native USB silicon routing; nothing to configure.
#define USB_D_MINUS     GPIO_NUM_19
#define USB_D_PLUS      GPIO_NUM_20

// -------------------- GPIOs livres no esquema --------------------
// #define GPIO_SPARE_1    GPIO_NUM_1
// #define GPIO_SPARE_2    GPIO_NUM_38

// -------------------- Mux channel labels --------------------
// Logical multiplexer channel numbers, not GPIOs; unused elsewhere.
#define D0              0U
#define D1              1U
#define D2              2U
#define D3              3U
#define D4              4U
#define D5              5U
#define D6              6U
#define D7              7U

// -------------------- Flags indices --------------------
// Bit indices into the Flags_in/Flags_out bitmasks (lib/Flags), not
// hardware configuration — making these settings would only rename which
// bit means what, with no operational benefit and a real desync risk
// against code that assumes these fixed indices.
#define BTN1_idx            0
#define BTN2_idx            1
#define BTN3_idx            2
#define SENSOR_LEFT_idx     0
#define SENSOR_RIGHT_idx    1
#define LED0_idx            0
#define LED1_idx            1
#define LED2_idx            2
#define LED3_idx            3
#define MOTOR_LEFT_idx      0
#define MOTOR_RIGHT_idx     1

// remap the using the color
#define LED_BLUE            LED0_idx
#define LED_GREEN           LED1_idx
#define LED_YELLOW          LED2_idx
#define LED_RED             LED3_idx

#endif // SETTINGS_H
